# Generated by Django 5.1.5 on 2025-01-23 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='year',
            field=models.DateField(),
        ),
    ]
